"""add vote_type to votes

Revision ID: 9af1cc52845d
Revises: 58a52451f4a0
Create Date: 2025-09-18 20:47:43.842249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af1cc52845d'
down_revision: Union[str, Sequence[str], None] = '58a52451f4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('vote_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'vote_type')
    # ### end Alembic commands ###
